### ISSUE TITLE
비로그인 회원 Archive 등록 요청 이슈

### ISSUE THREAD

**Issue by Kodo92** [teamesa/kilometer_backend#103]
현재 서버 구성대로라면 비로그인 회원이 ` POST /api/archive`를 보낼 때 401 Exception을 반환하는 것이 아닌
`/oauth2/authorization/naver`로 Redirect 되고 있습니다!

네이버 로그인 성공시 My page로 Redirect되고 있는데 **비 로그인 회원이 Archive 등록을 눌렀을 때 비즈니스 로직 논의가 필요합니다**

생각해본 비즈니스 로직 입니다.

1. 프론트에서 회원 정보가 없는 사용자가 아카이브 기록하기 누를 경우 프론트 차원에서 예외처리
2. 프론트를 거치지 않고 백엔드로 직접 요청을 전송 (Postman 등)하는 경우 Naver redirect 유지

@azxca1731 @kimhan0421

**Comment by azxca1731** [comment]
으으으음 이거 그냥 401로 하는걸로 바꿔야할 것 같아요. 제가 진행할게용!
